name: Docker Image CI/CD

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Pobranie kodu z repozytorium
      - name: Checkout code
        uses: actions/checkout@v4

      # Logowanie do Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Budowanie obrazu Docker
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/devopsworld-app:latest .

      # Push obrazu do Docker Hub
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devopsworld-app:latest
